### ISSUE TITLE
Integrate Huggingface's nlp data downloader with jiant

### ISSUE THREAD

**Issue by jeswan** [jiant-dev/jiant#107]
https://github.com/huggingface/nlp provides an easy way to manage 100+ NLP datasets and many evaluation schemes. It is useful to use this library to download data in jiant.

**Describe the solution you'd like**
Implement a data loader script that fetches data using nlp.

**Comment by jeswan** [comment]
@zphang You mentioned offline that nlp may provide data in a different format than jiant is expecting. Could you expand on that?

**Comment by jeswan** [comment]
Planning to limit the scope of this feature to using `nlp.load_dataset`, and iterating through and saving to jsonl (or original file format?). @pyeres @zphang what are your thoughts on converting to a standard .jsonl format?

**Comment by zphang** [comment]
Basically any dataset that isn't in a `.jsonl` or simple text file format. The clearest example of this is the SQuAD-style tasks, which have a hierarchical `.json` data file, and more importantly almost every SQuAD-style task is distributed in that format.

For the ones that are simple but not in `.jsonl` (e.g. `.tsv`), we need to decide if we want to maintain the original formats, or modify the task data loading as well.

My recommendation is to use `nlp.load_dataset` for everything that is straightforward, and fall back to loading raw files for others and resolve on a case-by-case basis.

**Comment by zphang** [comment]
MultiRC is another such example. Any thoughts on whether we should convert now, or later?

**Comment by jeswan** [comment]
If the eventual goal is to completely rely on `nlp`, then it seems tedious and potentially redundant to convert back to the original format especially since `tokenize_and_cache.py` has been identified as an area of improvement. It seems reason as a first step to identify the datasets that can easily be integrated into `jiant` then revisit the data preprocessing pipeline.

**Comment by jeswan** [comment]
`nlp` has been integrated into `jiant` with in https://github.com/jiant-dev/jiant/pull/106. Any additional tasks from `nlp` can be integrated with the data downloader framework.
