### ISSUE TITLE
Add support for exporting SuperGLUE task test predictions in leaderboard submission format

### ISSUE THREAD

**Issue by pyeres** [jiant-dev/jiant#108]
This issue tracks progress on adding support for exporting SuperGLUE task test predictions in leaderboard submission format (see ["How do I use SuperGLUE"](https://super.gluebenchmark.com/faq) for details of submission format).

**Comment by pyeres** [comment]
**More context:** the SuperGLUE leaderboard expects task predictions to have a specific format. The details of the task help to determine this format, for example each line in the MultiRC task predictions jsonl file is expected to contain a json object that follows ["...the JSONL structure in the data, so that each line represents a single context paragraph; be sure to use the paragraph ID, question ID, and answer ID." ](https://super.gluebenchmark.com/faq) Here's an example line from the SuperGLUE submission sample data:

```
{
  "idx": 0,
  "passage": {
    "questions": [
      {
        "idx": 0,
        "answers": [
          {
            "idx": 0,
            "label": 0
          },
          {
            "idx": 1,
            "label": 0
          },
          {
            "idx": 2,
            "label": 0
          }
        ]
      },
      {
        "idx": 1,
        "answers": [
          {
            "idx": 3,
            "label": 0
          },
          {
            "idx": 4,
            "label": 0
          },
          {
            "idx": 5,
            "label": 0
          },
          {
            "idx": 6,
            "label": 0
          },
          {
            "idx": 7,
            "label": 0
          }
        ]
      }
    ]
  }
}
```

For other tasks in SuperGLUE the submission format is simpler — it's just a json object with an `idx` field (int) and a `label` field (int or string), like this:

```
{"idx": 0, "label": 0}
```

or

```
{"idx": 0, "label": "entailment"}
```

or 

```
{"idx": 1, "label": "true"}
```

**And more background**:
` jiant2` already has `--write_val_preds` and `--write_test_preds` options, and these save preds as arrays using torch.save. To format these preds into valid leaderboard submissions we need to do some more work (especially for MultiRC, which, as explained above has some special requirements). 

**Current plan:**
1. Add a new command line arg (`args.super_glue_format`) indicating that any task that has a SuperGLUE submission formatting method should have its predictions formatted for SuperGLUE leaderboard submission. 
2. [At this line](https://github.com/jiant-dev/jiant/blob/master/jiant/proj/main/runscript.py#L201) in runscript, add the check for `args.super_glue_format` and, for any SuperGLUE tasks in the `test_task_list`, apply the task's SuperGLUE prediction formatter (defined in step 3...) to translate the predictions and write them to the run dir in the expected format/filetype.
3. Add a SuperGLUE prediction formatter method to the task definitions for all the SuperGLUE tasks.

@jeswan, @zphang — please let me know if you have any recommendations for better ways to do this, or if you have any concerns about how this would extend to support the other leaderboard tasks.

**Comment by zphang** [comment]
My recommendation is to put the super-glue-format logic and running into a separate script. It is a specific requirement for a specific benchmark, and shouldn't be incorporated into the main runscript flow.

**Comment by pyeres** [comment]
> My recommendation is to put the super-glue-format logic and running into a separate script. It is a specific requirement for a specific benchmark, and shouldn't be incorporated into the main runscript flow.
> 
> Adding the prediction formatter to the tasks themselves is fine by me.

Thanks, @zphang — PR https://github.com/jiant-dev/jiant/pull/117 (now visible as a draft) tries to implement this way.
