### ISSUE TITLE
Create compreshensive list of supported datasets

### ISSUE THREAD

**Issue by zphang** [jiant-dev/jiant#152]
Between the dataset downloader, task names and "jiant task names", there're several definitions of tasks, and different amounts of support for each. We should create a page that documents the full list of supported tasks.

**Comment by jeswan** [comment]
I think a README.md in `jiant/tasks` with a alphabetically sorted list of tasks would suffice. We could autogenerate the list with a pre-commit hook.

**Comment by zphang** [comment]
I think it may be somewhat more complicated. E.g.

- Distinction between `squad` and `squad_v1`, `squad_v2`
- Distinction between `xnli` and `xnli_en`
- What datasets are available via downloader
- "General purpose" tasks like MLM

I'm thinking some kind of table that would hopefully not be too onerous to maintain.

**Comment by zphang** [comment]
Done. https://github.com/jiant-dev/jiant/blob/master/md_docs/tasks.md
