### ISSUE TITLE
How data from different datasets is fed to trainer?

### ISSUE THREAD

**Issue by djstrong** [jiant-dev/jiant#154]
If datasets have different sizes (like in https://colab.research.google.com/github/jiant-dev/jiant/blob/master/examples/notebooks/jiant_Multi_Task_Example.ipynb), what data is used in 1 epoch? Is every example used only once in one epoch? Is, in one backward pass, data from only one dataset?

**Comment by zphang** [comment]
Each batch, we sample one task from the set of tasks that we are training on, and do a forward/backward pass:

https://github.com/jiant-dev/jiant/blob/4bdb984fd16a3a15067e960dd1b94d4969a7435f/jiant/proj/main/runner.py#L95-L125

In cases where multiple tasks are being trained on, the idea of an epoch becomes a little more fuzzy. More often than not, we train for a fixed number of steps and sample uniformly from our set of tasks, although we have a number of different sampling strategies available.

**Comment by djstrong** [comment]
Great! I see sampling strategies here: https://github.com/jiant-dev/jiant/blob/master/jiant/proj/main/components/task_sampler.py
