### ISSUE TITLE
Don't use the old NYU GLUE dataset URLs 

### ISSUE THREAD

**Issue by sleepinyourhat** [jiant-dev/jiant#161]
Corresponding to this PR to jiant v1.x:

https://github.com/nyu-mll/jiant/pull/1112

**Comment by zphang** [comment]
We're currently using Hugging Face NLP to download GLUE data. Is there any change in the data, or is it just being hosted somewhere new?

**Comment by sleepinyourhat** [comment]
Oops—it's still an issue, since, but we should be able to close it once we next increment our HF version dependency.

**Comment by sleepinyourhat** [comment]
(cc @apsdehal)

**Comment by jeswan** [comment]
@sleepinyourhat Should I open a PR to change the GLUE urls for [`nlp`](https://github.com/huggingface/nlp/blob/master/datasets/glue/glue.py) or is someone already planning on doing that?

**Comment by sleepinyourhat** [comment]
Sure, if you already know where to look/edit. Thanks!

**Comment by jeswan** [comment]
Changes for `nlp` are currently in: https://github.com/jeswan/nlp/commit/b7d4a071d432592ded971e30ef73330529de25ce. Testing is currently failing due to https://github.com/huggingface/datasets/issues/575. I will open a PR when https://github.com/huggingface/datasets/issues/575 is resolved.

**Comment by jeswan** [comment]
Opened PR here: https://github.com/huggingface/datasets/pull/609

**Comment by sleepinyourhat** [comment]
Thanks!
