### ISSUE TITLE
Word markers for word-boundary alignment

### ISSUE THREAD

**Issue by pyeres** [jiant-dev/jiant#86]
jiant has functions to modify tokenizations "for better matching" during alignment (https://github.com/nyu-mll/jiant/commit/fc4577fcac1a408573c02bdc21c07f07a6022eb1). These functions modify casing, remove some meta symbols introduced by specific tokenizers, and add word-boundary tokens.

It seems clear how adjusting the character casing would be helpful before the character matching step. However, for the tasks (e.g., SPR1, SPR2, Coref) and tokenizers (RoBERTa) we've been working with recently, removing meta symbols and adding word-boundary tags does not significantly change the span projections.

**Request for comment:** in which tasks and contexts is meta-symbol removal and word-boundary-tag addition helpful?

**Comment by pyeres** [comment]
Tagging @iftenney (as author of nyu-mll/jiant@fc4577f).

**Comment by iftenney** [comment]
This is the sort of thing that I'd expect to not change much in the "average case", but there's some set of examples where it could be pathologically wrong and you'd miss these in aggregate metrics. The heuristic we use in the retokenize code isn't perfect - ideally, you could get offsets directly from the tokenizer as in https://github.com/tensorflow/text#offsets
